apiVersion: v1
kind: Service
metadata:
  labels:
    app: sponsors
  name: sponsors
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: sponsors
  type: NodePort
status:
  loadBalancer: { }
