apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: events
  name: events
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: events
  type: NodePort
status:
  loadBalancer: { }
